name: Destroy Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to destroy'
        required: true
        type: choice
        options:
        - dev
        - staging
        # prod is intentionally excluded for safety
      confirm:
        description: 'Type "DESTROY" to confirm'
        required: true
        type: string

env:
  DOTNET_VERSION: '6.0.x'

jobs:
  destroy-infrastructure:
    runs-on: ubuntu-latest
    name: Destroy Infrastructure
    
    steps:
    - name: Validate Confirmation
      run: |
        if [ "${{ github.event.inputs.confirm }}" != "DESTROY" ]; then
          echo "❌ Confirmation failed. You must type 'DESTROY' to proceed."
          exit 1
        fi
        echo "✅ Confirmation validated"
    
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore Infrastructure dependencies
      run: dotnet restore Infrastructure.csproj
    
    - name: Build Infrastructure
      run: dotnet build Infrastructure.csproj --configuration Release --no-restore
    
    - name: Install Pulumi CLI
      uses: pulumi/actions@v4
    
    - name: Configure Pulumi Stack
      run: |
        pulumi stack select ${{ github.event.inputs.environment }}
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
    
    - name: Configure Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Destroy Infrastructure
      uses: pulumi/actions@v4
      with:
        command: destroy
        stack-name: ${{ github.event.inputs.environment }}
        work-dir: .
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
    
    - name: Confirm Destruction
      run: |
        echo "🗑️ Infrastructure for ${{ github.event.inputs.environment }} has been destroyed"
        echo "All Azure resources have been removed" 